"""Frozen corpora, reproducible campaigns, and blind human evaluation."""

from open_hollywood_engine.evaluations.blind import (
    DEFAULT_COMPARISON_PAIRS,
    build_blind_bundle,
)
from open_hollywood_engine.evaluations.contracts import (
    BENCHMARK_SCHEMA_VERSION,
    CANONICAL_RUBRIC_NAME,
    CANONICAL_RUBRIC_VERSION,
    EVALUATION_WEIGHTS,
    HUMAN_REVIEW_SCHEMA_VERSION,
    BenchmarkCase,
    BenchmarkCaseResult,
    BenchmarkCaseStatus,
    BenchmarkCategory,
    BenchmarkCorpus,
    BenchmarkModelTarget,
    BenchmarkOutput,
    BenchmarkPlan,
    BenchmarkProfileSnapshot,
    BenchmarkPrompt,
    BenchmarkRunReport,
    BenchmarkSuccessCriteria,
    BenchmarkSummary,
    BenchmarkSystem,
    BenchmarkTargetMetrics,
    BlindAnswer,
    BlindAnswerKey,
    BlindComparison,
    BlindDocument,
    BlindPreference,
    BlindPublicBundle,
    CanonicalStoryScore,
    EvaluationDimension,
    FictionMaturity,
    HardGate,
    HumanComparisonReview,
    HumanReviewBundle,
    TargetWordCount,
    canonical_sha256,
)
from open_hollywood_engine.evaluations.corpus import (
    V01_CORPUS_ID,
    V01_PROMPT_COUNT,
    BenchmarkCorpusError,
    load_benchmark_corpus,
)
from open_hollywood_engine.evaluations.harness import (
    BenchmarkCaseExecutionError,
    BenchmarkCaseExecutor,
    BenchmarkReportCheckpoint,
    run_benchmark_plan,
)
from open_hollywood_engine.evaluations.planning import build_benchmark_plan
from open_hollywood_engine.evaluations.reporting import summarize_benchmark
from open_hollywood_engine.evaluations.reviews import (
    REVIEW_CSV_COLUMNS,
    parse_review_csvs,
    render_review_csv,
    render_review_guide,
)

__all__ = [
    "BENCHMARK_SCHEMA_VERSION",
    "CANONICAL_RUBRIC_NAME",
    "CANONICAL_RUBRIC_VERSION",
    "DEFAULT_COMPARISON_PAIRS",
    "EVALUATION_WEIGHTS",
    "HUMAN_REVIEW_SCHEMA_VERSION",
    "REVIEW_CSV_COLUMNS",
    "V01_CORPUS_ID",
    "V01_PROMPT_COUNT",
    "BenchmarkCase",
    "BenchmarkCaseExecutionError",
    "BenchmarkCaseExecutor",
    "BenchmarkCaseResult",
    "BenchmarkCaseStatus",
    "BenchmarkCategory",
    "BenchmarkCorpus",
    "BenchmarkCorpusError",
    "BenchmarkModelTarget",
    "BenchmarkOutput",
    "BenchmarkPlan",
    "BenchmarkProfileSnapshot",
    "BenchmarkPrompt",
    "BenchmarkReportCheckpoint",
    "BenchmarkRunReport",
    "BenchmarkSuccessCriteria",
    "BenchmarkSummary",
    "BenchmarkSystem",
    "BenchmarkTargetMetrics",
    "BlindAnswer",
    "BlindAnswerKey",
    "BlindComparison",
    "BlindDocument",
    "BlindPreference",
    "BlindPublicBundle",
    "CanonicalStoryScore",
    "EvaluationDimension",
    "FictionMaturity",
    "HardGate",
    "HumanComparisonReview",
    "HumanReviewBundle",
    "TargetWordCount",
    "build_benchmark_plan",
    "build_blind_bundle",
    "canonical_sha256",
    "load_benchmark_corpus",
    "parse_review_csvs",
    "render_review_csv",
    "render_review_guide",
    "run_benchmark_plan",
    "summarize_benchmark",
]
